export const statusLabels = {
  AVAILABLE: "出品中",
  NEGOTIATING: "交渉中",
  SOLD: "売却済み",
  CANCELLED: "取り下げ",
};

export const materialTypeLabels = {
  REQUIRED: "必須教材",
  REFERENCE: "参考書",
};

export const faculties = ["文学部", "経済学部", "法学部", "商学部", "理工学部"];

// すべて架空のデモアカウントで、実在する連絡先や認証情報は持たせない。
export const seedDemoUsers = [
  {
    id: "demo-user-suzuki",
    nickname: "A. Suzuki",
    faculty: "経済学部",
    department: "経済学科",
    year: 1,
    pointBalance: 5000,
    avatar: "A",
  },
  {
    id: "demo-user-tanaka",
    nickname: "S. Tanaka",
    faculty: "経済学部",
    department: "経済学科",
    year: 2,
    pointBalance: 3200,
    avatar: "T",
  },
  {
    id: "demo-user-sato",
    nickname: "M. Sato",
    faculty: "法学部",
    department: "法律学科",
    year: 2,
    pointBalance: 4100,
    avatar: "S",
  },
  {
    id: "demo-user-kato",
    nickname: "R. Kato",
    faculty: "理工学部",
    department: "学門 A",
    year: 1,
    pointBalance: 2800,
    avatar: "K",
  },
  {
    id: "demo-user-ito",
    nickname: "A. Ito",
    faculty: "商学部",
    department: "商学科",
    year: 2,
    pointBalance: 3600,
    avatar: "I",
  },
];

export const seedBooks = [
  {
    id: "book-economics-2025",
    title: "経済学入門",
    course: "経済学 I",
    faculty: "経済学部",
    department: "経済学科",
    targetYear: 1,
    usedYear: 2025,
    materialType: "REQUIRED",
    price: 1200,
    condition: "書き込み少なめ",
    status: "AVAILABLE",
    sellerId: "demo-user-tanaka",
    sellerName: "S. Tanaka",
    imageUrl: "assets/book-economics.svg",
    description: "日吉キャンパスの経済学 I で使用。表紙に軽い擦れがあります。",
  },
  {
    id: "book-civil-law-2024",
    title: "民法総則ケースブック",
    course: "民法総則",
    faculty: "法学部",
    department: "法律学科",
    targetYear: 2,
    usedYear: 2024,
    materialType: "REQUIRED",
    price: 1800,
    condition: "重要箇所にマーカーあり",
    status: "AVAILABLE",
    sellerId: "demo-user-sato",
    sellerName: "M. Sato",
    imageUrl: "assets/book-law.svg",
    description: "授業で扱った章に付箋跡があります。本文の破れはありません。",
  },
  {
    id: "book-linear-algebra-2025",
    title: "線形代数スタンダード",
    course: "線形代数",
    faculty: "理工学部",
    department: "学門 A",
    targetYear: 1,
    usedYear: 2025,
    materialType: "REFERENCE",
    price: 900,
    condition: "良好",
    status: "NEGOTIATING",
    sellerId: "demo-user-kato",
    sellerName: "R. Kato",
    imageUrl: "assets/book-math.svg",
    description: "演習問題の解説が多い参考書。購入相談中のため追加リクエストは停止中です。",
  },
  {
    id: "book-marketing-2023",
    title: "マーケティング基礎",
    course: "マーケティング論",
    faculty: "商学部",
    department: "商学科",
    targetYear: 2,
    usedYear: 2023,
    materialType: "REQUIRED",
    price: 700,
    condition: "使用感あり",
    status: "SOLD",
    sellerId: "demo-user-ito",
    sellerName: "A. Ito",
    imageUrl: "assets/book-business.svg",
    description: "過去年度版。取引成立済みのサンプルとして表示しています。",
  },
];
